# Generated by Django 2.2.3 on 2019-07-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ('title',), 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
