# Generated by Django 2.2.3 on 2019-07-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190705_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating_count',
            field=models.IntegerField(default=1),
        ),
    ]
