# Generated by Django 2.2.3 on 2019-07-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190704_1843'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='movies',
            field=models.ManyToManyField(to='movies.Movies'),
        ),
    ]
