# Generated by Django 2.2.3 on 2019-07-04 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190705_0335'),
        ('users', '0002_userprofile_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='movies',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='movies',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='movies.Movies'),
        ),
    ]
