# Generated by Django 2.2.3 on 2019-07-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190705_0335'),
        ('users', '0003_auto_20190705_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='movies',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='movies',
            field=models.ManyToManyField(to='movies.Movies'),
        ),
    ]
